# Generated by Django 3.1.7 on 2021-03-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_title', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=30)),
            ],
        ),
    ]
