# Generated by Django 3.1.7 on 2021-03-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_auto_20210302_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='first_title',
            new_name='title',
        ),
    ]
